# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/elasticable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/elasticable.proto',
  package='com.hypefactors.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17proto/elasticable.proto\x12\x18\x63om.hypefactors.messages\"\xd1\x01\n\x0b\x45lasticable\x12\x0e\n\x06_index\x18\x01 \x01(\t\x12\r\n\x05_type\x18\x02 \x01(\t\x12\x0b\n\x03_id\x18\x03 \x01(\t\x12\x0f\n\x07_source\x18\x04 \x01(\t\x12\x43\n\n_operation\x18\x05 \x01(\x0e\x32/.com.hypefactors.messages.Elasticable.Operation\x12\x0f\n\x07_script\x18\x06 \x01(\t\"/\n\tOperation\x12\n\n\x06UPSERT\x10\x00\x12\n\n\x06\x43REATE\x10\x01\x12\n\n\x06SCRIPT\x10\x02\x62\x06proto3')
)



_ELASTICABLE_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='com.hypefactors.messages.Elasticable.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UPSERT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCRIPT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=216,
  serialized_end=263,
)
_sym_db.RegisterEnumDescriptor(_ELASTICABLE_OPERATION)


_ELASTICABLE = _descriptor.Descriptor(
  name='Elasticable',
  full_name='com.hypefactors.messages.Elasticable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_index', full_name='com.hypefactors.messages.Elasticable._index', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_type', full_name='com.hypefactors.messages.Elasticable._type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_id', full_name='com.hypefactors.messages.Elasticable._id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_source', full_name='com.hypefactors.messages.Elasticable._source', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_operation', full_name='com.hypefactors.messages.Elasticable._operation', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_script', full_name='com.hypefactors.messages.Elasticable._script', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ELASTICABLE_OPERATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=263,
)

_ELASTICABLE.fields_by_name['_operation'].enum_type = _ELASTICABLE_OPERATION
_ELASTICABLE_OPERATION.containing_type = _ELASTICABLE
DESCRIPTOR.message_types_by_name['Elasticable'] = _ELASTICABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Elasticable = _reflection.GeneratedProtocolMessageType('Elasticable', (_message.Message,), dict(
  DESCRIPTOR = _ELASTICABLE,
  __module__ = 'proto.elasticable_pb2'
  # @@protoc_insertion_point(class_scope:com.hypefactors.messages.Elasticable)
  ))
_sym_db.RegisterMessage(Elasticable)


# @@protoc_insertion_point(module_scope)
